/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testcrud;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.xml.soap.MessageFactory;

/**
 *
 * @author Akito
 */
public class Main extends javax.swing.JFrame {
    String nol_jam = "";
    String nol_menit = "";
    String nol_detik = "";
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        selectData();
        setTanggal();
        setJam();
        
        
    }
    
    public void setTanggal(){
    java.util.Date skrg = new java.util.Date();
    java.text.SimpleDateFormat kal = new SimpleDateFormat("dd/MM/yyyy");
    labelTanggal.setText(kal.format(skrg));
    
    }
    
    public void setJam(){
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if (nilai_jam <= 9) {
                    nol_jam = "0";
                }
                if (nilai_menit <=9) {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                labelJam.setText("Jam "+jam+ ":" + menit +":"+detik);
            }
        };
    new Timer(100, taskPerformer).start();
    
    }
    
    public void selectData(){
            String kolom[] = {"NIS","NamaSiswa","JenisKelamin","Kelas","Email","Alamat","TempatLahir","TanggalLahir"};
            DefaultTableModel dtm = new DefaultTableModel(null, kolom);
            String SQL = "SELECT * FROM t_siswa";
            ResultSet rs = KoneksiDB.executeQuery(SQL);
            try {
                while (rs.next()) {
                    String NIS = rs.getString(1);
                    String NamaSiswa = rs.getString(2);
                    String JenisKelamin = "";
                    if ("L".equals(rs.getString(3))) {
                        JenisKelamin = "Laki-Laki";
                    }else{
                        JenisKelamin = "Perempuan";
                    }
                    String Kelas= rs.getString(4);
                    String Email = rs.getString(5);
                    String ALamat = rs.getString(6);
                    String Tempat = rs.getString(7);
                    String Tanggal = rs.getString(8).toString();
                    String data[] = {NIS,NamaSiswa,JenisKelamin,Kelas,Email,ALamat,Tempat,Tanggal};
                    dtm.addRow(data);
                }
        } catch (SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
            tabelData.setModel(dtm);
        }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelTanggal = new javax.swing.JLabel();
        labelJam = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        NIS = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NAMA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        laki = new javax.swing.JRadioButton();
        Perem = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        Kelas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Alamat = new javax.swing.JTextArea();
        tempatL = new javax.swing.JTextField();
        tanggalL = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Edit = new javax.swing.JButton();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM BIODATA SISWA SMKTELKOM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 20, 380, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("The Real Informatic Schools");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 54, 310, 20);
        jPanel1.add(labelTanggal);
        labelTanggal.setBounds(800, 30, 110, 30);
        jPanel1.add(labelJam);
        labelJam.setBounds(800, 60, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 930, 100);

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel3.setText("NIS");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(12, 13, 120, 14);
        jPanel2.add(NIS);
        NIS.setBounds(10, 30, 210, 30);

        jLabel4.setText("Nama");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 70, 140, 14);
        jPanel2.add(NAMA);
        NAMA.setBounds(10, 90, 210, 30);

        jLabel5.setText("Jenis Kelamin");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 250, 140, 14);

        laki.setBackground(new java.awt.Color(102, 255, 102));
        buttonGroup1.add(laki);
        laki.setText("Laki-Laki");
        laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiActionPerformed(evt);
            }
        });
        jPanel2.add(laki);
        laki.setBounds(10, 270, 90, 23);

        Perem.setBackground(new java.awt.Color(102, 255, 102));
        buttonGroup1.add(Perem);
        Perem.setText("Perempuan");
        jPanel2.add(Perem);
        Perem.setBounds(110, 270, 110, 23);

        jLabel6.setText("Kelas");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 300, 130, 14);
        jPanel2.add(Kelas);
        Kelas.setBounds(10, 320, 210, 30);

        jLabel7.setText("Email");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 360, 140, 14);
        jPanel2.add(Email);
        Email.setBounds(10, 380, 210, 30);

        jLabel8.setText("Alamat");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 420, 170, 14);

        Alamat.setColumns(20);
        Alamat.setRows(5);
        jScrollPane1.setViewportView(Alamat);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 440, 210, 96);
        jPanel2.add(tempatL);
        tempatL.setBounds(10, 150, 210, 30);

        tanggalL.setText("Tanggal Lahir");
        jPanel2.add(tanggalL);
        tanggalL.setBounds(10, 190, 140, 14);

        tanggal.setDateFormatString("dd-mm-yyyy");
        jPanel2.add(tanggal);
        tanggal.setBounds(10, 210, 210, 30);

        jLabel10.setText("Tempat Lahir");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 130, 140, 14);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 110, 230, 550);

        jPanel3.setBackground(new java.awt.Color(102, 255, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        jPanel3.add(Edit);
        Edit.setBounds(410, 20, 80, 30);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel3.add(save);
        save.setBounds(50, 20, 80, 30);

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel3.add(delete);
        delete.setBounds(140, 20, 80, 30);

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel3.add(clear);
        clear.setBounds(230, 20, 80, 30);

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel3.add(refresh);
        refresh.setBounds(320, 20, 80, 30);

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel3.add(print);
        print.setBounds(500, 20, 80, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(250, 110, 660, 70);

        jPanel4.setBackground(new java.awt.Color(102, 255, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama Siswa", "Jenis Kelamin", "Kelas", "Email", "Alamat", "Tempat Lahir", "Tanggal Lahir"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelData);
        if (tabelData.getColumnModel().getColumnCount() > 0) {
            tabelData.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 640, 450);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(250, 190, 660, 470);

        setBounds(0, 0, 937, 713);
    }// </editor-fold>//GEN-END:initComponents

    private void lakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggalan = dateFormat.format(tanggal.getDate());
        String JK = "";
                if(laki.isSelected()){
                    JK = "L";
                }else{
                    JK = "P";
                }
                
        if ("".equals(NIS.getText()) || "".equals(Alamat.getText()) || JK.equals("") || "".equals(Kelas.getText()) || "".equals(NAMA.getText()) || tempatL.equals("") || tanggalan.equals("") || "".equals(Email.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","ERROR", JOptionPane.WARNING_MESSAGE);
        }else{
            
                
                String SQL = "INSERT INTO t_siswa (NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat,TempatLahir,TanggalLahir) " + "VALUES('"+NIS.getText()+"','"+NAMA.getText()+"','"+JK+"','"+Kelas.getText()+"','"+Email.getText()+"','"+Alamat.getText()+"','"+tempatL.getText()+"','"+tanggalan+"')";
                
                int status = KoneksiDB.execute(SQL);
                if (status == 1) {
                
                    JOptionPane.showMessageDialog(this, "Data berhasil Di tambahkan", "Sukses",JOptionPane.INFORMATION_MESSAGE);
                    selectData();
                    setTanggal();
                    setJam();
            }else{
                    JOptionPane.showMessageDialog(this, "Data gagal Di tambahkan", "Gagal",JOptionPane.WARNING_MESSAGE);
                }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int baris = tabelData.getSelectedRow();
        if (baris != 1) {
            String NIS = tabelData.getValueAt(baris,0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                
                    JOptionPane.showMessageDialog(this, "Data berhasil Di hapus", "Sukses",JOptionPane.INFORMATION_MESSAGE);
                   
                    
            }else{
                    JOptionPane.showMessageDialog(this, "Data gagal Di Hapus", "Gagal",JOptionPane.WARNING_MESSAGE);
                }
       }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "ERROR",JOptionPane.WARNING_MESSAGE);
        }
        setTanggal();
        setJam();
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        NAMA.setText("");
        NIS.setText("");
        Kelas.setText("");
        buttonGroup1.clearSelection();
        Email.setText("");
        Alamat.setText("");
        tempatL.setText("");
        tanggal.setDate(null);
        setTanggal();
            setJam();
    }//GEN-LAST:event_clearActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        selectData();
        setTanggal();
            setJam();
    }//GEN-LAST:event_refreshActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggalan = dateFormat.format(tanggal.getDate());
        String JK;
        if ("".equals(NIS.getText()) || "".equals(Alamat.getText()) || "".equals(Kelas.getText()) || "".equals(NAMA.getText()) || "".equals(Email.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","ERROR", JOptionPane.WARNING_MESSAGE);
        }else{
            //String JK = "";
                if(laki.isSelected()){
                    JK = "L";
                }else{
                    JK = "P";
                }
                
                String SQL = "UPDATE t_siswa SET NIS='"+NIS.getText()+"',"+ "NamaSiswa='"+NAMA.getText()+"',"+ "JenisKelamin='"+JK+"',"+ "Kelas='"+Kelas.getText()+"',"+ "Email='"+Email.getText()+"',"+ "Alamat='"+Alamat.getText()+"',"+"TempatLahir='"+tempatL.getText()+"',"+"TanggalLahir='"+tanggalan+"' WHERE NIS='"+NIS.getText()+"'" ;
                
                int status = KoneksiDB.execute(SQL);
                if (status == 1) {
                
                    JOptionPane.showMessageDialog(this, "Data berhasil Di tambahkan", "Sukses",JOptionPane.INFORMATION_MESSAGE);
                    selectData();
            }else{
                    JOptionPane.showMessageDialog(this, "Data gagal Di tambahkan", "Gagal",JOptionPane.WARNING_MESSAGE);
                }
        }
        setTanggal();
            setJam();
    }//GEN-LAST:event_EditActionPerformed

    private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
        // TODO add your handling code here:
        int baris = tabelData.getSelectedRow();

        if (baris != -1) {
            NIS.setText(tabelData.getValueAt(baris, 0).toString());
            NAMA.setText(tabelData.getValueAt(baris, 1).toString());
            if ("Laki-Laki".equals(tabelData.getValueAt(baris, 2).toString())) {
                laki.setSelected(true);
            }else{
                Perem.setSelected(true);
            }
            Kelas.setText(tabelData.getValueAt(baris, 3).toString());
            Email.setText(tabelData.getValueAt(baris, 4).toString());
            Alamat.setText(tabelData.getValueAt(baris, 5).toString());
            tempatL.setText(tabelData.getValueAt(baris, 6).toString());
            SimpleDateFormat date = new SimpleDateFormat("yyyy-mm-dd");
            Date dateFormat = null;
            try {
            dateFormat = date.parse(tabelData.getValueAt(baris, 7).toString());
            } catch (ParseException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            tanggal.setDate(dateFormat);

            setTanggal();
            setJam();
        }
    }//GEN-LAST:event_tabelDataMouseClicked

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Biodata Siswa SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page (0,number,integer)     ");
        
        try {
            tabelData.print(JTable.PrintMode.FIT_WIDTH, header, footer,true,null,true,null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot Print %s%n", e.getMessage());
        }
        setTanggal();
            setJam();
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Alamat;
    private javax.swing.JButton Edit;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Kelas;
    private javax.swing.JTextField NAMA;
    private javax.swing.JTextField NIS;
    private javax.swing.JRadioButton Perem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelJam;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JRadioButton laki;
    private javax.swing.JButton print;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JTable tabelData;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JLabel tanggalL;
    private javax.swing.JTextField tempatL;
    // End of variables declaration//GEN-END:variables
}
